# Generated by Django 2.2.4 on 2019-08-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='name',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(blank=True, default=False, verbose_name='É da equipe?'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(verbose_name='Último login'),
        ),
        migrations.DeleteModel(
            name='PasswordReset',
        ),
    ]
