# Generated by Django 2.2.4 on 2019-08-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20190820_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(null=True, verbose_name='Último login'),
        ),
    ]
